# Generated by Django 4.1 on 2022-10-20 06:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('logo_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'kbase_article_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.PositiveBigIntegerField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField(null=True)),
                ('file_name', models.FileField(upload_to='')),
                ('thumbnail', models.ImageField(upload_to='mowrknowledgerepo/static/img')),
                ('is_published', models.BooleanField(null=True)),
                ('source', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=500)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('entry_by', models.CharField(max_length=100)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_article_details',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePublishCategory',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kbase_article_pub_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DataAccessCategory',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lkp_data_access_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DataCategory',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('parent', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'lkp_data_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('mailing_address', models.CharField(blank=True, max_length=200)),
                ('web_address', models.URLField(blank=True, max_length=50)),
                ('organization_chief', models.CharField(blank=True, max_length=100)),
                ('chief_designation', models.CharField(blank=True, max_length=50)),
                ('focal_person', models.CharField(blank=True, max_length=50)),
                ('fp_designation', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('mobile_no', models.CharField(blank=True, max_length=14)),
                ('logo', models.ImageField(blank=True, upload_to='mowrknowledgerepo/static/img')),
            ],
            options={
                'db_table': 'lkp_organizations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.PositiveBigIntegerField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField(null=True)),
                ('file_name', models.FileField(max_length=500, upload_to='')),
                ('thumbnail', models.ImageField(null=True, upload_to='mowrknowledgerepo/static/img')),
                ('keywords', models.CharField(max_length=1000)),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('entry_by', models.CharField(max_length=100)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(max_length=100)),
                ('access_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.dataaccesscategory')),
                ('data_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.datacategory')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.organization')),
            ],
            options={
                'db_table': 'tbl_documents',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='datacategory',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.organization'),
        ),
        migrations.CreateModel(
            name='ArticleDocDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.articledetail')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.document')),
            ],
            options={
                'db_table': 'tbl_article_doc_details',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='articledetail',
            name='access_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.dataaccesscategory'),
        ),
        migrations.AddField(
            model_name='articledetail',
            name='data_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.datacategory'),
        ),
        migrations.AddField(
            model_name='articledetail',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.organization'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_id', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('article_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.articlecategory')),
                ('publish_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.articlepublishcategory')),
            ],
            options={
                'db_table': 'kbase_articles',
                'ordering': ['id'],
            },
        ),
    ]
