# Generated by Django 4.1 on 2022-08-16 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePublishCategory',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('parent_id', models.SmallIntegerField(null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('publish_category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.articlepublishcategory')),
            ],
        ),
    ]
