# Generated by Django 4.1 on 2022-08-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='kbase_articles',
        ),
        migrations.AlterModelTable(
            name='articlepublishcategory',
            table='kbase_article_pub_categories',
        ),
    ]
