# Generated by Django 4.1 on 2022-10-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='access_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.dataaccesscategory'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='data_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.datacategory'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='entry_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='static/article'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='is_published',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.organization'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='parent_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='entry_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='static/document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='parent_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='static/logo'),
        ),
    ]
