# Generated by Django 4.1 on 2022-08-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0002_alter_article_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.articlepublishcategory'),
        ),
    ]
