# Generated by Django 4.1 on 2022-10-31 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0003_alter_articledetail_publication_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCommonCategory',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lkp_data_common_categories',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='sorting_order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datacategory',
            name='data_common_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.datacommoncategory'),
        ),
    ]
