# Generated by Django 4.1 on 2022-11-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_datacommoncategory_organization_sorting_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetail',
            name='is_parent_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_parent_available',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
