# Generated by Django 4.1 on 2022-08-24 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_articlecategory_article_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='articlepublishcategory',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='logo_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent_id',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
