# Generated by Django 4.1 on 2022-11-30 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0005_articledetail_is_parent_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLinkCategory',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lkp_important_link_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('web_link', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('entry_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('delete_status', models.BooleanField(blank=True, null=True)),
                ('link_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.importantlinkcategory')),
            ],
            options={
                'db_table': 'tbl_important_links',
                'ordering': ['id'],
            },
        ),
    ]
