# Generated by Django 4.1 on 2022-10-02 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0005_alter_article_options_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.PositiveBigIntegerField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField(null=True)),
                ('file_name', models.FileField(upload_to='')),
                ('thumbnail', models.ImageField(upload_to='mowrknowledgerepo/static/img')),
                ('is_published', models.BooleanField(null=True)),
                ('source', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=500)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('entry_by', models.CharField(max_length=100)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_article_details',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DataAccessCategory',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lkp_data_access_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DataCategory',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('parent', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'lkp_data_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('mailing_address', models.CharField(max_length=200)),
                ('web_address', models.URLField(max_length=50)),
                ('organization_chief', models.CharField(max_length=100)),
                ('chief_designation', models.CharField(max_length=50)),
                ('focal_person', models.CharField(max_length=50)),
                ('fp_designation', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=14)),
                ('logo', models.ImageField(upload_to='mowrknowledgerepo/static/img')),
            ],
            options={
                'db_table': 'lkp_organizations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.PositiveBigIntegerField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField(null=True)),
                ('file_name', models.FileField(upload_to='')),
                ('thumbnail', models.ImageField(upload_to='mowrknowledgerepo/static/img')),
                ('keywords', models.CharField(max_length=500)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('entry_by', models.CharField(max_length=100)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(max_length=100)),
                ('access_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.dataaccesscategory')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.datacategory')),
                ('organization_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.organization')),
            ],
            options={
                'db_table': 'tbl_documents',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='datacategory',
            name='organization_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.organization'),
        ),
        migrations.CreateModel(
            name='ArticleDocDetail',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('article_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.articledetail')),
                ('document_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.document')),
            ],
            options={
                'db_table': 'tbl_article_doc_details',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='articledetail',
            name='access_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.dataaccesscategory'),
        ),
        migrations.AddField(
            model_name='articledetail',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.datacategory'),
        ),
        migrations.AddField(
            model_name='articledetail',
            name='organization_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.organization'),
        ),
    ]
