# Generated by Django 4.1 on 2022-10-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0006_articledetail_dataaccesscategory_datacategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articledetail',
            old_name='access_category_id',
            new_name='access_category',
        ),
        migrations.RenameField(
            model_name='articledetail',
            old_name='category_id',
            new_name='data_category',
        ),
        migrations.RenameField(
            model_name='articledetail',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='articledocdetail',
            old_name='article_id',
            new_name='article_detail',
        ),
        migrations.RenameField(
            model_name='articledocdetail',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='datacategory',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='access_category_id',
            new_name='access_category',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='category_id',
            new_name='data_category',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
