# Generated by Django 4.1.3 on 2023-03-29 06:18

from django.db import migrations, models
import django.db.models.deletion
import knowledgebase.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0006_importantlinkcategory_importantlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Organization Types',
                'db_table': 'lkp_organization_types',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['id'], 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.AlterModelOptions(
            name='articlepublishcategory',
            options={'ordering': ['id'], 'verbose_name_plural': 'Article Publish Categories'},
        ),
        migrations.AlterModelOptions(
            name='dataaccesscategory',
            options={'ordering': ['id'], 'verbose_name_plural': 'Data Access Categories'},
        ),
        migrations.AlterModelOptions(
            name='datacategory',
            options={'ordering': ['id'], 'verbose_name_plural': 'Data Categories'},
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=knowledgebase.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=knowledgebase.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.organizationtype'),
        ),
    ]
