# Generated by Django 4.1 on 2022-10-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0007_rename_access_category_id_articledetail_access_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='mowrknowledgerepo/static/img'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='chief_designation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='focal_person',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fp_designation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='mowrknowledgerepo/static/img'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_chief',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='web_address',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
