# Generated by Django 4.1 on 2023-04-26 06:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import knowledgebase.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0007_organizationtype_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=knowledgebase.models.get_upload_path_thumb),
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=knowledgebase.models.get_document_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), knowledgebase.models.MaxSizeValidator(10485760)], verbose_name='Upload file (Maximum 10MB)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_files', to='knowledgebase.document')),
            ],
            options={
                'db_table': 'tbl_document_files',
                'ordering': ['id'],
            },
        ),
    ]
