# Generated by Django 4.1 on 2023-04-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0008_alter_document_thumbnail_documentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
