# Generated by Django 4.1 on 2023-05-02 08:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import knowledgebase.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0009_alter_document_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentApprovalStatus',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('approval_state', models.PositiveIntegerField()),
                ('approval_state_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Document Approval Status',
                'db_table': 'lkp_document_approval_status',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='documentfile',
            options={'ordering': ['id'], 'verbose_name': 'Upload Document'},
        ),
        migrations.AlterField(
            model_name='document',
            name='access_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.dataaccesscategory', verbose_name='Access Category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='data_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.datacategory', verbose_name='Data Category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='entry_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entry By'),
        ),
        migrations.AlterField(
            model_name='document',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modify By'),
        ),
        migrations.AlterField(
            model_name='document',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=knowledgebase.models.get_upload_path_thumb, verbose_name='Upload Thumbnail'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=knowledgebase.models.get_document_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), knowledgebase.models.MaxSizeValidator(10485760)], verbose_name='Select File (Maximum 10MB)'),
        ),
    ]
