# Generated by Django 4.1 on 2023-05-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0010_documentapprovalstatus_alter_documentfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentapprovalstatus',
            options={'ordering': ['id'], 'verbose_name_plural': 'Document Approval Status'},
        ),
        migrations.AlterField(
            model_name='documentapprovalstatus',
            name='approval_state',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
