# Generated by Django 4.1 on 2023-05-02 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0011_alter_documentapprovalstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_approval_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.documentapprovalstatus', to_field='approval_state', verbose_name='Approval Status'),
        ),
    ]
