# Generated by Django 4.1 on 2023-06-04 09:59

import django.core.validators
from django.db import migrations, models
import knowledgebase.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0012_document_document_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=knowledgebase.models.get_document_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), knowledgebase.models.MaxSizeValidator(26214400)], verbose_name='Select File (Maximum 25MB)'),
        ),
    ]
