# Generated by Django 4.1 on 2023-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0013_alter_documentfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
