# Generated by Django 4.1 on 2023-06-05 03:14

from django.db import migrations, models
import django.db.models.deletion
import knowledgebase.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0014_alter_document_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDetail',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('file_name', models.FileField(blank=True, max_length=500, null=True, upload_to=knowledgebase.models.get_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=knowledgebase.models.get_upload_path_thumb, verbose_name='Upload Thumbnail')),
                ('keywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('entry_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entry By')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modify By')),
                ('is_parent_available', models.BooleanField(blank=True, null=True)),
                ('parent_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('access_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.dataaccesscategory', verbose_name='Access Category')),
                ('data_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.datacategory', verbose_name='Data Category')),
                ('document_approval_status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.documentapprovalstatus', to_field='approval_state', verbose_name='Approval Status')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledgebase.organization')),
            ],
            options={
                'db_table': 'tbl_document_details',
                'ordering': ['id'],
            },
        ),
    ]
