# Generated by Django 4.1 on 2023-06-05 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0015_documentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_files', to='knowledgebase.documentdetail'),
        ),
    ]
