# Generated by Django 4.1 on 2023-06-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0021_documentfiledetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentFile',
        ),
    ]
