# Generated by Django 4.1 on 2023-06-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0023_documentfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentFileDetails',
        ),
    ]
